### ISSUE TITLE
AWS Lambda Environment fails to find S3EventNotification** class. Works locally

### ISSUE THREAD

**Issue by flipch** [aws/aws-lambda-java-libs#262]
https://github.com/aws/aws-lambda-java-libs/blob/3ab22135a35c7ae2c52e062acf6cf5202af434a4/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/serializers/S3EventSerializer.java#L103-L114

Something seems to be failing here when trying to find the `com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification**` classes as my lambda clearly has them available. I've exported from the AWS Console and extracted the jar file.

![image](https://user-images.githubusercontent.com/10780503/127044221-e53d7629-0013-4fe4-b192-1de4586b7d35.png)

Yet I still get a runtime error when attempting to deserialize a string into an `S3Event`

```
java.lang.ClassNotFoundException: com.amazonaws.services.s3.event.S3EventNotification$S3EventNotificationRecord: com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil$ReflectException
com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil$ReflectException: java.lang.ClassNotFoundException: com.amazonaws.services.s3.event.S3EventNotification$S3EventNotificationRecord
        at com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil.loadClass(ReflectUtil.java:85)
        at com.amazonaws.services.lambda.runtime.serialization.util.SerializeUtil.loadCustomerClass(SerializeUtil.java:37)
        at com.amazonaws.services.lambda.runtime.serialization.events.serializers.S3EventSerializer.deserializeEvent(S3EventSerializer.java:157)
        at com.amazonaws.services.lambda.runtime.serialization.events.serializers.S3EventSerializer.fromJson(S3EventSerializer.java:93)
```

Or when instantiating an deserializer for `S3EventNotificationRecord`
```
java.lang.ClassNotFoundException: org.joda.time.DateTime: com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil$ReflectException
com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil$ReflectException: java.lang.ClassNotFoundException: org.joda.time.DateTime
        at com.amazonaws.services.lambda.runtime.serialization.util.ReflectUtil.loadClass(ReflectUtil.java:85)
        at com.amazonaws.services.lambda.runtime.serialization.util.SerializeUtil.loadCustomerClass(SerializeUtil.java:37)
        at com.amazonaws.services.lambda.runtime.serialization.events.modules.DateTimeModule.<init>(DateTimeModule.java:28)
        at com.amazonaws.services.lambda.runtime.serialization.events.LambdaEventSerializers.serializerFor(LambdaEventSerializers.java:248)
        ```

**Comment by flipch** [comment]
The issue seems to revolve around the lambda's environment class loader not functioning properly.

The solution was to change the passed in class loader, i.e from 
`this.s3EventSerializer = LambdaEventSerializers.serializerFor(S3EventNotification.class,
        Thread.currentThread().getContextClassLoader());`
to
`this.s3EventSerializer = LambdaEventSerializers.serializerFor(S3EventNotification.class,
        Thread.currentThread().getContextClassLoader());`

**Comment by kedarundale17** [comment]
@flipch I faced the same issue , the above mentioned solution works like a charm.
Thanks

**Comment by shinusuresh** [comment]
2024 yey
