### ISSUE TITLE
GraalVM support for aws-lambda-java-runtime-interface-client

### ISSUE THREAD

**Issue by msailes** [aws/aws-lambda-java-libs#272]
Developers wanting to adopt the aws-lambda-java-runtime-interface-client for their own projects which use GraalVM native-image find integration difficult. This is because this project does not include the required jni and reflection configuration files.

Developers have to include this configuration in their own projects, which is an additional complexity and burden.

**Comment by ilopmar** [comment]
We did a few tests in Micronaut sometime ago to use this library and it would be really helpful to include all the configuration in the library.

**Comment by olegz** [comment]
[Spring Cloud Functions](https://github.com/spring-cloud/spring-cloud-function) has implemented its own polling loop for Custom Runtime (for now). We would like to adopt the AWS one to reduce the amount of code we support and instead colaborate and contribute to single AWS code base. However we would prefer NOT to include the required GraalVM configs in our project and instead see if we can help and suggest code changes on yoru end that would make it GraalVM friendly. As the matter of fact, for the past several months we have been going through this effort in all Spring projects to make our code _GraalVM friendly_ whenever we can (i.e., eliminating certain refection calls, @Autowired annotation etc.). And only when something is absolutely not-refactorable (ragrdless of the reason), then as Mark implied, the required configs should come from the framework.

**Comment by stejsj** [comment]
Been struggling for a weak or two making graalvm working with the runtime client based on samples on github.

This is very important for jvm targetted language since cold start is a very big problem (giving end users and developers a bad customer experience) 

We were actually quite near having to select another language than Scala and that would have been a big pain for us.

We believe in the serverless world and are big fans of AWS services combined with Scala, witch actually try to add the same value to the developer. Do more with less effort and faster and as bonus saving manhours and money in the long run.

 Graalvm and native images are a perfect fit for all jvm languages since the jvm wasn't build for short lived processes. 
 
 Thank you in advance 
 Steffen

**Comment by alexanderankin** [comment]
Are there any key developments to link to this thread for newcomers trying to create aws lambda/graalvm projects, to this the newest issue about the topic? I found [this](https://github.com/aws/aws-lambda-java-libs/issues/205) from googling my errors, it seems like there is still missing metadata, or it is just not clear where to find the libraries supplying it.

**Comment by msailes** [comment]
Hi @alexanderankin,

I would start with this sample project and adapt from there.

https://github.com/aws-samples/serverless-graalvm-demo

Thanks,

**Comment by NikolayMetchev** [comment]
does anybody have an update to date jni-config.json?

**Comment by NikolayMetchev** [comment]
I am getting the following error: 
```
Exception in thread "main" java.lang.Error: java.lang.NullPointerException
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:192)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:180)
Caused by: java.lang.NullPointerException
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1274)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:432)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:71)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:132)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:204)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:160)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:97)
at java.base@17.0.9/java.lang.ClassLoader.loadLibrary(ClassLoader.java:57)
at java.base@17.0.9/java.lang.Runtime.load0(Runtime.java:755)
at java.base@17.0.9/java.lang.System.load(System.java:1953)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.JniHelper.unpackAndLoad(JniHelper.java:51)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.JniHelper.load(JniHelper.java:38)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.NativeClient.init(NativeClient.java:16)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.LambdaRuntimeApiClientImpl.<init>(LambdaRuntimeApiClientImpl.java:41)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:203)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190)
... 1 more
```

**Comment by WtfJoke** [comment]
@NikolayMetchev not sure if its still up to date, but 10 months ago I've made that sample project to test different cold start performance with jdk 21 https://github.com/WtfJoke/graalvm-java-21-lambda

The `jni-config.json` can be found here (but I think its identical with the one [mentioned above](https://github.com/aws/aws-lambda-java-libs/issues/272#issuecomment-1408236375)): 
https://github.com/WtfJoke/graalvm-java-21-lambda/blob/main/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json

**Comment by smirnoal** [comment]
@NikolayMetchev we added new JNI calls in recent RIC versions to clean up DNS cache ([link](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-runtime-interface-client/src/main/jni/com_amazonaws_services_lambda_crac_DNSManager.cpp#L16-L21)). I guess this is why you are seeing the exception

**Comment by NikolayMetchev** [comment]
Thanks,
It would be good to get this issue looked at. GraalVM seems to be a popular choice for lambda developers..I managed to actually use graalvm to generate a jni-config.json for me. It had a lot of stuff in there...

**Comment by francis-a** [comment]
I'm seeing the same exception when using `aws-lambda-java-runtime-interface-client:2.6.0`. I believe it is also in 2.5.1 and 2.5.0.

```
java.lang.NullPointerException
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:192)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:180)
at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.NullPointerException
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1354)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:452)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:70)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:131)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:128)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:84)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibrary0(NativeLibraries.java:147)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryAbsolute(NativeLibraries.java:102)
at java.base@22.0.2/java.lang.ClassLoader.loadLibrary(ClassLoader.java:114)
at java.base@22.0.2/java.lang.Runtime.load0(Runtime.java:852)
at java.base@22.0.2/java.lang.System.load(System.java:2030)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.JniHelper.unpackAndLoad(JniHelper.java:51)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.JniHelper.load(JniHelper.java:38)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.NativeClient.init(NativeClient.java:16)
at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.LambdaRuntimeApiClientImpl.<init>(LambdaRuntimeApiClientImpl.java:41)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:203)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190)
... 2 more
```

The only workaround I've been able to come up with is to downgrade to `aws-lambda-java-runtime-interface-client:2.4.2`

**Comment by astsiatsko** [comment]
> Thanks, It would be good to get this issue looked at. GraalVM seems to be a popular choice for lambda developers..I managed to actually use graalvm to generate a jni-config.json for me. It had a lot of stuff in there...

Hi, how did you manage to generate the jni config? I see the same error, jni-config from demo does not work...

**Comment by astsiatsko** [comment]
> I'm seeing the same exception when using `aws-lambda-java-runtime-interface-client:2.6.0`. I believe it is also in 2.5.1 and 2.5.0.
> 
> ```
> java.lang.NullPointerException
> at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:192)
> at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:180)
> at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
> Caused by: java.lang.NullPointerException
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1354)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:452)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:70)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:131)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:128)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:84)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibrary0(NativeLibraries.java:147)
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryAbsolute(NativeLibraries.java:102)
> at java.base@22.0.2/java.lang.ClassLoader.loadLibrary(ClassLoader.java:114)
> at java.base@22.0.2/java.lang.Runtime.load0(Runtime.java:852)
> at java.base@22.0.2/java.lang.System.load(System.java:2030)
> at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.JniHelper.unpackAndLoad(JniHelper.java:51)
> at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.JniHelper.load(JniHelper.java:38)
> at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.NativeClient.init(NativeClient.java:16)
> at com.amazonaws.services.lambda.runtime.api.client.runtimeapi.LambdaRuntimeApiClientImpl.<init>(LambdaRuntimeApiClientImpl.java:41)
> at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:203)
> at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190)
> ... 2 more
> ```
> 
> The only workaround I've been able to come up with is to downgrade to `aws-lambda-java-runtime-interface-client:2.4.2`
> 
> [francis-a/passhelper@79fe14d](https://github.com/francis-a/passhelper/commit/79fe14d7d98e72df04a398771f196609a7e34f06)

Thanks, unfortunately it didn't work for me. Can you share your config please? pom.xml, etc

**Comment by Mikeeyy** [comment]
In version 2.8.7, the issue is still present. The application still fails with the following exception:

```
Caused by: java.lang.NullPointerException
    at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1274)
```

The only workaround seems to be downgrading to 2.4.2 as @francis-a mentioned. It appears that this regression has been occurring since the 2.5.x releases.

Are there any plans from the AWS team to prioritize a fix for this issue?

**Comment by Dzeri96** [comment]
I'm trying the `aws-lambda-java-runtime-interface-client` v2.10.1 and have the same problem. There's really so much conflicting and scattered information out there on creating a working native image for Lambda.

Edit: I pretty much gave up on native images for Lambda, but I do have a fix for the error I had, which is that the `tenantId` field was not exposed in `com.amazonaws.services.lambda.runtime.api.client.runtimeapi.dto.InvocationRequest`. The way to solve it is to add it to the jni-config.json of aws-lambda-java-runtime-interface-client from the example repo like so:
```
[
  {
    "name":"com.amazonaws.services.lambda.runtime.api.client.runtimeapi.LambdaRuntimeClientException",
    "methods":[{"name":"<init>","parameterTypes":["java.lang.String","int"] }]
  },
  {
    "name":"com.amazonaws.services.lambda.runtime.api.client.runtimeapi.dto.InvocationRequest",
    "fields":[{"name":"id"}, {"name":"invokedFunctionArn"}, {"name":"deadlineTimeInMs"}, {"name":"xrayTraceId"}, {"name":"clientContext"}, {"name":"cognitoIdentity"}, {"name":"content"}, {"name": "tenantId"}],
    "allPublicMethods":true
  },
  {
    "name":"java.lang.Boolean",
    "methods":[{"name":"getBoolean","parameterTypes":["java.lang.String"] }]
  }

]
```
