### ISSUE TITLE
Deserialization of ScheduledEvent fails on Joda time during test

### ISSUE THREAD

**Issue by shaddyz** [aws/aws-lambda-java-libs#47]
I'm geting an exception during an integration test where my Lambda function accepts a ScheduledEvent. When I set a value for "time", I get the following exception:

```
An error occurred during JSON parsing: java.lang.RuntimeException
java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: java.io.UncheckedIOException: com.fasterxml.jackson.databind.JsonMappingException: java.lang.reflect.InvocationTargetException (through reference chain: com.amazonaws.services.lambda.runtime.events.ScheduledEvent["time"])
Caused by: com.fasterxml.jackson.databind.JsonMappingException: java.lang.reflect.InvocationTargetException (through reference chain: com.amazonaws.services.lambda.runtime.events.ScheduledEvent["time"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1474)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)
Caused by: lambdainternal.util.ReflectUtil$ReflectException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.NullPointerException
at org.joda.time.format.DateTimeFormatterBuilder$CharacterLiteral.parseInto(DateTimeFormatterBuilder.java:1224)
at org.joda.time.format.DateTimeFormatterBuilder$Composite.parseInto(DateTimeFormatterBuilder.java:2490)
at org.joda.time.format.InternalParserDateTimeParser.parseInto(InternalParserDateTimeParser.java:52)
at org.joda.time.format.DateTimeFormatterBuilder$MatchingParser.parseInto(DateTimeFormatterBuilder.java:2584)
at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:925)
at org.joda.time.DateTime.parse(DateTime.java:160)
at org.joda.time.DateTime.parse(DateTime.java:149)
... 4 more
`

**Comment by msailes** [comment]
Hi Shaddy,

I just tried to recreate this error with the following handler and couldn't

```
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.ScheduledEvent;

public class App implements RequestHandler<ScheduledEvent, Object> {

    public Object handleRequest(final ScheduledEvent scheduledEvent, final Context context) {
```

Could you provide any more detail on what you're doing? 

Thanks,

**Comment by shaddyz** [comment]
Is that the complete code you’re using to repro?

**Comment by msailes** [comment]
This is the complete code, it just prints the event out to the Lambda logger.

```
package helloworld;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.ScheduledEvent;

/**
 * Handler for requests to Lambda function.
 */
public class App implements RequestHandler<ScheduledEvent, Object> {

    public Object handleRequest(final ScheduledEvent scheduledEvent, final Context context) {
        
        context.getLogger().log(scheduledEvent.toString());
        
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        headers.put("X-Custom-Header", "application/json");
        try {
            final String pageContents = this.getPageContents("https://checkip.amazonaws.com");
            String output = String.format("{ \"message\": \"hello world\", \"location\": \"%s\" }", pageContents);
            return new GatewayResponse(output, headers, 200);
        } catch (IOException e) {
            return new GatewayResponse("{}", headers, 500);
        }
    }

    private String getPageContents(String address) throws IOException{
        URL url = new URL(address);
        try(BufferedReader br = new BufferedReader(new InputStreamReader(url.openStream()))) {
            return br.lines().collect(Collectors.joining(System.lineSeparator()));
        }
    }
}

```

**Comment by junhaowww** [comment]
Any update on this one?

**Comment by msailes** [comment]
Hi junhaowww,

Can you tell me more about the problem you're having? And where you're seeing the issue.

Thanks,

**Comment by rmfaheem** [comment]
Hi everyone,

I have encountered 2 issues with the `ScheduledEvent` class in version `3.4.0` of the lib `aws-lambda-java-events`, both only occurring when using the `RequestStreamHandler` interface. 

But for some reason, when using `RequestHandler<ScheduledEvent, Object>` the event is mapped correctly

Outdated Mapping (easily worked-around)
---

The first issue I have is the event mapping seems to be outdated. The event I am receiving is like this:
```
{
  "version": "0",
  "id": "89d1a02d-5ec7-412e-82f5-13505f849b41",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "2016-12-30T18:44:49Z",
  "region": "us-east-1",
  "resources": [
    "arn:aws:events:us-east-1:123456789012:rule/SampleRule"
  ],
  "detail": {}
}
```

But the mapping is as follows:
```
public class ScheduledEvent implements Serializable, Cloneable {
  private String account;
  private String region;
  private Map<String, Object> detail;
  private String detailType;
  private String source;
  private String id;
  private DateTime time;
  private List<String> resources;
}
```
As you can see, field `version` is not present. 

Of course, this issue is simply resolve by configuring jackson to ignore unrecognized properties.

Unparse-able 'time' field.
---
The second issue is what I believe is the same as, if not related to, what @shaddyz is experiencing. The date in the event fails to map to the `DateTime` object time. But it maps successfully to the `Date` object.

And here is the error:
```
Cannot format given Object as a Date: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(Unknown Source)
	at java.base/java.text.Format.format(Unknown Source)
	at 
```

**Comment by jeromevdl** [comment]
Using the recently released [aws-lambda-java-serialization](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-serialization), you should avoid this kind of serialisation problem, as it is the exact same code used by the Java Lambda runtime. 
And if you want to ease even more your tests, you can have a look at [aws-lambda-java-tests](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-tests), that has just been released in that purpose. 
Please tell us if that helps.

**Comment by deeTEEcee** [comment]
fyi i get this similar error if i set up a scheduled rule and trigger a lambda :/

**Comment by harpsichordagreed** [comment]
@forkercat https://stackdev.space/questions/encountering-a-nullpointerexception-while-trying-to-parse-nested-json-structures
